# Swagger2访问URL
# http://localhost:8888/hst/swagger-ui.html

#服务器
server:
  port: 8888
  servlet:
    context-path: /hst

#Spring组件
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#测试
test:
  flg: true